version: '3.3'
services:
  caddy:
    image: caddy:2.6.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./public:/app/public
      - ./ui/dist:/app/ui/dist
      - ./.docker/caddy/data:/data
      - ./.docker/caddy/config:/config
      - ./.docker/log/caddy:/var/log/caddy
    extra_hosts:
      - 'dev.server:127.0.0.1'
    depends_on:
      - php

  php:
    build: ./.docker/php
    restart: unless-stopped
    environment:
      - "MYSQL_HOST=${MYSQL_HOST}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    volumes:
      - .:/app/
      - ./.docker/log/php:/var/log/
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.10.2
    restart: unless-stopped
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - 3306:3306
    volumes:
      - ./.docker/db:/var/lib/mysql/
      - ./.docker/log/mysql:/var/log/
    command: --sql_mode=''

  redis:
    image: redis:7.0.5
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "20"
    restart: unless-stopped

  node:
    build: ./.docker/node
    restart: unless-stopped
    tty: true
    extra_hosts:
      - 'dev.server:127.0.0.1'
    volumes:
      - .:/app/
    ports:
      - 5173:5173
      - 8080:8080
